export const COMMENT_REQUEST = 'COMMENT_REQUEST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILURE = 'COMMENT_FAILURE';


export const GET_ALLCOMMENT_REQUEST = 'GET_ALLCOMMENT_REQUEST';
export const GET_ALLCOMMENT_SUCCESS =  'GET_ALLCOMMENT_SUCCESS';
export const GET_ALLCOMMENT_FAILURE = 'GET_ALLCOMMENT_FAILURE';
