export const COMMENT_REQUEST = 'COMMENT_REQUEST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILURE = 'COMMENT_FAILURE';


export const GET_ALLCOMMENT_REQUEST = 'GET_ALLCOMMENT_REQUEST';
export const GET_ALLCOMMENT_SUCCESS =  'GET_ALLCOMMENT_SUCCESS';
export const GET_ALLCOMMENT_FAILURE = 'GET_ALLCOMMENT_FAILURE';

export const DISLIKE_REQUEST = 'DISLIKE_REQUEST';
export const DISLIKE_SUCCESS = 'DISLIKE_SUCCESS';
export const DISLIKE_FAILURE = 'DISLIKE_FAILURE';

export const LIKE_REQUEST = 'LIKE_REQUEST';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_FAILURE = 'LIKE_FAILURE';

export const GET_COMMENT_DETAIL_REQUEST = 'GET_COMMENT_DETAIL_REQUEST';
export const GET_COMMENT_DETAIL_SUCCESS = 'GET_COMMENT_DETAIL_SUCCESS';
export const GET_COMMENT_DETAIL_FAILURE = 'GET_COMMENT_DETAIL_FAILURE';

